"""Generate non-UI summary and measured Phase 1A review from retained evidence."""
import json
import statistics
import sys
from collections import Counter
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from pipeline.snapshot import write_json
from pipeline.validation import assert_schema_freeze
from pipeline.diff import compare

ROOT=Path(__file__).resolve().parents[1]
def read(path): return json.loads((ROOT/path).read_text(encoding='utf-8'))
def main():
    assert_schema_freeze()
    runs=[json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT/'data/reports/observation').glob('*.json'))]
    success=[r for r in runs if r['observation_status']=='SUCCESS']; failures=[r for r in runs if r['observation_status']=='FAILED']
    domains=read('data/registry/business_domains.json')['rules']; taxonomy=read('data/seed/business_domains.json')['domains']
    primary=Counter(r['primary_domain'] for r in domains if r['primary_domain']); membership=Counter(d for r in domains for d in ([r['primary_domain']] if r['primary_domain'] else [])+r['secondary_domains'])
    state=read('data/registry/state.json'); rules=read('public/api/v1/rules.json')['rules']; manifest=read('public/api/v1/manifest.json')
    latest=read('public/api/v1/changes/latest.json')['events']; future=read('public/api/v1/changes/upcoming.json')['events']; tests=read('data/reports/tests.json'); recovery=read('data/reports/observation_recovery.json')
    examples=[]
    for cid in ('admrul-36282','admrul-36283','admrul-35334','law-001668'):
        s=state['snapshots'][cid]; archived=[json.loads(p.read_text(encoding='utf-8')) for p in (ROOT/'data/snapshots'/cid).glob('*.json')]
        older=[v for v in archived if v['metadata']['effective_date']<s['metadata']['effective_date']]
        old=max(older,key=lambda v:v['metadata']['effective_date']) if older else None
        examples.append({'canonical_id':cid,'current_name':s['metadata']['name'],'current_effective_date':s['metadata']['effective_date'],'current_version_id':s['version_id'],'official_source_url':s['official_source_url'],'older_version_id':old['version_id'] if old else None,'comparison_event_types':sorted(set(e['change_type'] for e in compare(old,s,'2026-10-03T00:00:00+00:00'))) if old else [],'upcoming_effective_dates':[v['metadata']['effective_date'] for v in state['future'].get(cid,[])]})
    consistency=bool(success) and all(r['publication_status']=='NO_CHANGE' and r['event_ids_identical'] and r['public_bytes_and_mtimes_identical'] and r['change_count']==0 for r in success)
    hashes=bool(success) and all(r['snapshot_hashes_identical'] for r in success)
    good=tests['passed'] and tests['public_contract']['status']=='PASS' and tests['secret_scan']['status']=='PASS' and consistency and hashes and recovery['status']=='PASS' and len(rules)==68
    report={'title':'PHASE 1A STABILITY & DOMAIN REVIEW','observation_runs':runs,'successful_live_runs':len(success),'live_failed_attempts':len(failures),'failure_context':'Three OFFICIAL_PAGE_FAILED attempts under restricted execution networking before permitted runs; zero API requests in those attempts. Retained, not omitted.','upstream_api_errors_in_successful_runs':sum(sum(r['transport_error_summary'].values()) for r in success),'no_change_consistency':'PASS' if consistency else 'FAIL','hash_stability':'PASS' if hashes else 'FAIL','fail_closed_recovery':recovery['status'],'api_calls_per_run':[r['api_request_count'] for r in success],'official_page_calls_per_run':[r['public_page_request_count'] for r in success],'average_run_seconds':round(statistics.mean(r['duration_seconds'] for r in success),3),'average_api_response_seconds':round(sum(r['api_response_seconds'] for r in success)/sum(r['api_request_count'] for r in success),6),'retry_count':sum(r['retry_count'] for r in success),'twice_daily_api_calls':2*max(r['api_request_count'] for r in success),'twice_daily_total_http_calls':2*max(r['total_http_request_count'] for r in success),'core_rules':len(rules),'domain_classification':{'classified':sum(r['review_status']=='REVIEWED' for r in domains),'multi_domain':sum(bool(r['secondary_domains']) for r in domains),'review':sum(r['review_status']=='REVIEW' for r in domains)},'domain_distribution':{d:{'primary_count':primary[d],'related_membership_count':membership[d]} for d in taxonomy},'api_v1_candidate':bool(good and manifest['API_V1_CANDIDATE']),'schema_version':manifest['schema_version'],'dataset_version':manifest['dataset_version'],'web_ready':bool(good),'android_contract_ready':bool(good),'tests':tests,'current_real_examples':examples,'risks':['Same-session observations only; no multi-day soak or official quota guarantee.','Two broad reporting classifications await business-owner review; reviewed mappings are evidence review, not agency approval.','Future client compilation, hosting atomic release and separate live operational health remain untested.'],'next_step':'Review two pending domain mappings and arrange multi-day observation. Frontend implementation requires a subsequent request; no UI or Firebase deployment in Phase 1A.'}
    write_json(ROOT/'data/reports/phase1a.json',report)
    preview=['# 공개 요약 미리보기 — 관련 업무 분야','','정적 검토 보고서이며 UI 구현물이 아닙니다. 분야는 공식 변경의 검색·정리를 위한 연결이며 법적 업무 지시가 아닙니다.','','| 관련 업무 분야 | 주 분야 규정 수 | 주·보조 포함 규정 수 |','|---|---:|---:|']
    preview += [f'| {d} | {primary[d]} | {membership[d]} |' for d in taxonomy]
    preview += ['',f'미분류 REVIEW: {report["domain_classification"]["review"]}개. 주 분야 합계 {sum(primary.values())}개; 보조 포함 열은 중복 집계됩니다.','',f'최근 변경: 현재 관찰된 변경 이벤트 {len(latest)}건. 최초 기준 데이터의 과거 개정은 새 이벤트로 만들지 않았습니다.',f'시행 예정: {sum(len(v) for v in state["future"].values())}개 버전 / 이벤트 {len(future)}건.',f'폐지: {sum(r["status"]=="REPEALED" for r in rules)}개. 공식 폐지 근거 확인.',f'변경 없음: 최근 정상 관찰에서 {success[-1]["success_count"]}개 / 새 변경 {success[-1]["change_count"]}건. 폐지·시행 예정 상태도 변경 없음과 함께 존재할 수 있습니다.','','## 현재 공식 버전 예시','','아래는 과거 개정 이력 예시이며 이번 실행에서 새로 발생한 변경으로 표시하지 않습니다.','','| 규정 | 현행 시행일 | 시행 예정 | 구·신 비교 |','|---|---|---|---|']
    preview += [f'| {e["current_name"]} | {e["current_effective_date"]} | {", ".join(e["upcoming_effective_dates"]) or "—"} | {", ".join(e["comparison_event_types"])} |' for e in examples]
    (ROOT/'data/reports/summary_preview.md').write_text('\n'.join(preview)+'\n',encoding='utf-8')
    lines=['# PHASE 1A STABILITY & DOMAIN REVIEW','','OBSERVATION RUNS:','', '| Run | Seconds | API / pages | Success / review / failure | Change | Publication |','|---|---:|---:|---:|---:|---|']
    lines += [f'| {r["run_id"]} | {r["duration_seconds"]} | {r["api_request_count"]} / {r["public_page_request_count"]} | {r["success_count"]} / {r["review_count"]} / {r["failure_count"]} | {r["change_count"]} | {r["publication_status"]} |' for r in runs if r['observation_status']!='RUNNING']
    lines += ['',f'LIVE FAILURES: {len(failures)} restricted-execution page failures; 0 API calls in those attempts. Successful permitted runs: {len(success)}; transport/API errors: {report["upstream_api_errors_in_successful_runs"]}.',f'NO_CHANGE CONSISTENCY: {report["no_change_consistency"]}',f'HASH STABILITY: {report["hash_stability"]}',f'FAIL-CLOSED RECOVERY: {report["fail_closed_recovery"]}',f'API CALLS PER RUN: {report["api_calls_per_run"]}; official page calls: {report["official_page_calls_per_run"]}',f'AVERAGE RUN TIME: {report["average_run_seconds"]} seconds',f'AVERAGE API RESPONSE TIME: {report["average_api_response_seconds"]} seconds; retries: {report["retry_count"]}',f'TWICE DAILY: {report["twice_daily_api_calls"]} API requests / {report["twice_daily_total_http_calls"]} total HTTP requests. Measured wall time approximately {2*report["average_run_seconds"]:.1f} seconds/day; not an official quota guarantee.','CORE RULES: 68',f'DOMAIN CLASSIFICATION: {report["domain_classification"]}','','DOMAIN DISTRIBUTION:','',*preview[4:21],'',f'API V1 CANDIDATE: {"YES" if report["api_v1_candidate"] else "NO"}',f'WEB READY: {"YES" if good else "NO"}',f'ANDROID CONTRACT READY: {"YES" if good else "NO"}',f'TESTS: {tests["tests"]} / {"PASS" if tests["passed"] else "FAIL"}; public schemas: {tests["public_contract"]["validated_file_count"]} files; secret leaks: {tests["secret_scan"]["file_count"]}','', 'The explicit schema 1.0 → 1.1/domain migration published one dataset with zero new legal events. All live observations themselves were NO_CHANGE. Version references and evidence classifications are frozen before client development.','','RISKS:','',*['- '+r for r in report['risks']],'','NEXT STEP: '+report['next_step'],'','Details: phase1a.json; summary_preview.md; observation/*.json; observation_recovery.json; docs/api_v1_candidate.md.']
    (ROOT/'data/reports/phase1a.md').write_text('\n\n'.join(lines[:1])+'\n'+'\n'.join(lines[1:])+'\n',encoding='utf-8')
    print(json.dumps({k:report[k] for k in ('successful_live_runs','no_change_consistency','hash_stability','domain_classification','average_run_seconds','api_v1_candidate','web_ready','android_contract_ready')},ensure_ascii=False))

if __name__=='__main__': main()
