"""Measured production-hardening report; cloud activation is not inferred."""
import json
import subprocess
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from pipeline.snapshot import write_json
from pipeline.validation import assert_schema_freeze
from scripts.verify import scan_secret

ROOT=Path(__file__).resolve().parents[1]
def read(path): return json.loads((ROOT/path).read_text(encoding='utf-8'))
def main():
    assert_schema_freeze()
    tests=read('data/reports/tests.json'); frontend=read('data/reports/frontend_phase1b.json'); artifact=read('data/reports/firebase_artifact.json'); workflow=read('data/reports/workflows.json'); manifest=read('public/api/v1/manifest.json')
    runs=[json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT/'data/reports/production').glob('*.json'))]
    stable=[r for r in runs if r['result']=='NO_CHANGE' and r['dataset_version']==manifest['dataset_version']]
    nochange=bool(stable) and all(r['public_bytes_and_mtimes_identical'] and r['snapshot_hashes_identical'] and r['event_ids_identical'] for r in stable)
    secrets=scan_secret(); archived=[]
    for p in (ROOT/'data/staging').glob('backup-*'):
        if (p/'manifest.json').is_file() and json.loads((p/'manifest.json').read_text(encoding='utf-8'))['schema_version']=='1.1': archived.append(p)
    archive_report={'status':'NOT_CHECKED','files':0}
    if archived:
        previous=max(archived,key=lambda p:p.stat().st_mtime_ns); files=list(previous.glob('rules/*/versions/*.json'))
        preserved=all((ROOT/'public/api/v1'/p.relative_to(previous)).read_bytes()==p.read_bytes() for p in files)
        archive_report={'status':'PASS' if preserved else 'FAIL','files':len(files)}
    code_ready=bool(tests['passed'] and frontend['success'] and artifact['status']=='PASS' and workflow['status']=='PASS' and nochange and secrets['status']=='PASS')
    remote_names=subprocess.run(['git','remote'],cwd=ROOT,capture_output=True,text=True).stdout.splitlines()
    report={'title':'PHASE 1B PRODUCTION HARDENING','backend_change_derivation':'PASS' if tests['passed'] else 'FAIL','timezone_contract':'PASS' if tests['passed'] and frontend['success'] else 'FAIL','sync_cron':{'kst':['08:37','20:37'],'utc':['37 23 * * *','37 11 * * *']},'api_calls_before':{'law_api':159,'official_pages':70,'duration_seconds':199.332,'source':'Phase 1A measured full observations'},'api_calls_after':{'core_law_api':90,'core_official_pages':0,'daily_discovery_extra_pages':2,'full_weekly_audit_baseline_api_estimate':159,'full_weekly_audit_pages_estimate':72,'core_api_reduction_percent':round((159-90)/159*100,2)},'seed_discovery_frequency':'Daily morning table scan; immediate full resolution on table changes; Sunday full outgoing-link identity audit. Hidden link-target drift may take up to a week absent outages.','last_good':'PASS' if tests['passed'] else 'FAIL','no_change':'PASS' if nochange else 'FAIL','github_actions':workflow['status'],'github_actions_scope':'STATIC_VALIDATION_ONLY; not executed on GitHub','heartbeat_30day':'PASS' if tests['passed'] else 'FAIL','firebase_artifact':artifact,'firebase_cache_policy':workflow['firebase_cache_policy'],'secret_leak':secrets,'android_contract':'PASS' if tests['passed'] else 'FAIL','backend_tests':tests,'frontend_tests':{'passed':frontend['numPassedTests'],'total':frontend['numTotalTests'],'success':frontend['success']},'build':'PASS' if artifact['status']=='PASS' else 'FAIL','schema_version':manifest['schema_version'],'immutable_archive_format':'1.1','archive_preservation':archive_report,'dataset_version':manifest['dataset_version'],'live_runs':runs,'stabilized_no_change_runs':len(stable),'prepared_code_ready':code_ready,'ready_for_firebase_deployment':False,'activation_prerequisites':['Configure/push a default-branch GitHub repository and permit allowlisted bot commits.','Set LAW_API_OC and FIREBASE_SERVICE_ACCOUNT GitHub secrets.','Set intended FIREBASE_PROJECT_ID and verify Hosting service account permissions/default site.','Enable PRODUCTION_PIPELINE_ENABLED only after target/credentials review; hosted Actions/deployment are untested.'],'git_remote_configured':bool(remote_names),'deployment_performed':False}
    write_json(ROOT/'data/reports/phase1b.json',report)
    lines=['# PHASE 1B PRODUCTION HARDENING','',f'BACKEND CHANGE DERIVATION: {report["backend_change_derivation"]}',f'TIMEZONE CONTRACT: {report["timezone_contract"]}','SYNC CRON: KST 08:37 / 20:37; UTC 37 23 * * * / 37 11 * * *','API CALLS BEFORE: 159 API + 70 official pages; average 199.332 seconds','API CALLS AFTER: 90 API + 0 pages for core; daily discovery adds 2 pages. 43.40% API reduction.','SEED DISCOVERY FREQUENCY: daily tables, immediate full resolution on table changes, Sunday full outgoing-link audit. Weekly figures are baseline estimates, not newly measured full-audit runs.',f'LAST-GOOD: {report["last_good"]}',f'NO_CHANGE: {report["no_change"]}; {len(stable)} final stable live runs',f'GITHUB ACTIONS: {report["github_actions"]} (static validation; gated, not activated)',f'30-DAY HEARTBEAT: {report["heartbeat_30day"]}; only data/ops/heartbeat.json on idle NO_CHANGE runs',f'FIREBASE ARTIFACT: {artifact["status"]}; {artifact["artifact_file_count"]} files, including {artifact["api"]["validated_files"]} validated API JSON files',f'FIREBASE CACHE POLICY: {report["firebase_cache_policy"]}',f'SECRET LEAK: {secrets["file_count"]}',f'ANDROID CONTRACT: {report["android_contract"]}',f'BACKEND TESTS: {tests["tests"]} / {"PASS" if tests["passed"] else "FAIL"}',f'FRONTEND TESTS: {frontend["numPassedTests"]}/{frontend["numTotalTests"]} PASS',f'BUILD: {report["build"]}','READY FOR FIREBASE DEPLOYMENT: NO — code/artifact ready; external target, GitHub credentials/push policy and cloud execution not verified.','', '## Measured live runs','','| Started UTC | Mode | API / pages | Seconds | Result | New legal events |','|---|---|---:|---:|---|---:|']
    lines += [f'| {r["started_at"]} | {r["mode"]} | {r["api_request_count"]} / {r["public_page_request_count"]} | {r["duration_seconds"]} | {r["result"]} | {r["new_events"]} |' for r in runs]
    lines += ['', 'Development PUBLISHED runs reflect explicit 1.2 comparison-format refinements, with zero new legal events. Final unchanged runs preserve bytes/mtimes, hashes and IDs. Prior archive format 1.1 remains byte-identical.',f'Archive preservation: {archive_report["status"]}; {archive_report["files"]} original archive files compared.','','## Remaining activation work','',*['- '+item for item in report['activation_prerequisites']],'','No Firebase deployment, remote push or frontend redesign was performed. Same-session stability only; multi-day observation and real hosted IAM/cache checks remain outstanding. Fixed historical fixtures prevent effective-date rollover from breaking unattended CI. Public health remains published-dataset health; private last_attempt/last_successful_sync and request metrics reflect each attempt.','', 'Details: phase1b.json, production/*.json, frontend_phase1b.json, workflows.json, firebase_artifact.json, docs/phase1b_operations.md and docs/phase1b_contract.md.']
    (ROOT/'data/reports/phase1b.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(json.dumps({k:report[k] for k in ('backend_change_derivation','no_change','stabilized_no_change_runs','prepared_code_ready','ready_for_firebase_deployment')},ensure_ascii=False))
if __name__=='__main__': main()
